# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

random_array = np.random.rand(3, 3, 3)
print(random_array)


[[[0.87720598 0.69946079 0.26707184]
  [0.38722809 0.56067626 0.13240431]
  [0.93132747 0.35527766 0.85622044]]

 [[0.32731197 0.10277206 0.58156474]
  [0.72435465 0.93356842 0.03393548]
  [0.97309379 0.56759404 0.11048338]]

 [[0.86084765 0.58310043 0.22666963]
  [0.16569497 0.35474713 0.54001939]
  [0.66002343 0.33811475 0.24829807]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [2]:
import numpy as np
matrix = np.zeros((5, 5))
values = [1, 2, 3, 4]
np.fill_diagonal(matrix[1:], values)
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1 
matrix[::2, 1::2] = 1 
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
import numpy as np
random_matrix = np.random.rand(5, 5)
min_value = random_matrix.min()
max_value = random_matrix.max()
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.48767412 0.46516453 0.63145108 0.04065497 0.41948865]
 [0.95180203 0.79769613 0.98194299 0.03423215 0.1198928 ]
 [0.71788289 0.8635316  0.46291037 0.94931855 0.30043736]
 [0.38783113 0.78181828 0.24791989 0.86526084 0.17454203]
 [0.78974992 0.1115671  0.58171173 0.5471133  0.63925746]]

Normalized Matrix:
[[0.47846025 0.45470872 0.63016998 0.00677719 0.40651271]
 [0.96819603 0.80558747 1.         0.         0.0903869 ]
 [0.7213706  0.87505535 0.45233018 0.96557553 0.28089286]
 [0.37310851 0.78883358 0.22547778 0.87688    0.14805136]
 [0.79720283 0.08160184 0.57768631 0.54117894 0.63840708]]


# 5. How to find common values between two arrays?

In [7]:
import numpy as np
array1 = np.array([2, 5, 7, 8, 9])
array2 = np.array([3, 2, 5, 8, 7])
common_values = np.intersect1d(array1, array2)
print("Common Values:", common_values)

Common Values: [2 5 7 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [10]:
import numpy as np
A = np.random.rand(5)
B = np.random.rand(5)
are_equal = np.array_equal(A, B)
if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0


In [14]:
import numpy as np
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print("Original Vector:")
print(random_vector)


Original Vector:
[0.16147818 0.95078975 0.43584364 0.32067263 0.93500444 0.
 0.84073168 0.46690496 0.15915157 0.82855964]


# 9. How to print all the values of an array?


In [16]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
for i in array:
    print(i, end=' ')

1 2 3 4 5 

# 10.Subtract the mean of each row of a matrix


In [20]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)
matrix_minus_means = matrix - row_means

print("Original Matrix:")
print(matrix)
print()
print('row_means: ')
print(row_means)
print()
print("\nMatrix with Row Means Subtracted:")
print(matrix_minus_means)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

row_means: 
[[2.]
 [5.]
 [8.]]


Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [24]:
import numpy as np
given_vector = np.array([1, 2, 3, 4, 5])
indices_vector = np.array([1, 3, 2, 1, 0])
result_vector = given_vector.copy()
result_vector[indices_vector] += 1
print("Given Vector:", given_vector)
print("Result Vector:", result_vector)


Given Vector: [1 2 3 4 5]
Result Vector: [2 3 4 5 5]


# 12.How to get the diagonal of a dot product?

In [26]:
import numpy as np

matrix1 = np.array([[3, 2, 1],
                    [2, 1, 6],
                    [9, 8, 7]])

matrix2 = np.array([[5, 8, 2],
                    [6, 9, 7],
                    [4, 2, 3]])
dot_product = np.dot(matrix1, matrix2)
diagonal = np.diag(dot_product)

print("Matrix1:")
print(matrix1)

print("\nMatrix2:")
print(matrix2)

print("\nDot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)


Matrix1:
[[3 2 1]
 [2 1 6]
 [9 8 7]]

Matrix2:
[[5 8 2]
 [6 9 7]
 [4 2 3]]

Dot Product:
[[ 31  44  23]
 [ 40  37  29]
 [121 158  95]]

Diagonal of Dot Product:
[31 37 95]


# 13.How to find the most frequent value in an array?

In [32]:
import numpy as np
x = np.random.randint(0, 10, 50)
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
print("Array:", x)
print("\nMost Frequent Value:", most_frequent_value)
print("Count:", counts[most_frequent_value])


Array: [0 3 4 7 7 6 2 2 3 6 4 8 8 5 9 0 7 7 7 5 4 5 2 5 6 0 1 7 5 6 7 1 1 1 1 9 7
 5 9 5 4 5 6 0 9 5 7 5 9 2]

Most Frequent Value: 5
Count: 10


# 14.How to get the n largest values of an array


In [34]:
import numpy as np
array = np.array([46,25,22,49,57,6,53,65])
n = 5
pindices = np.argpartition(-array, n)[:n]
n_large = array[pindices]
print("Original array:", array)
print(f"{n} largest values:", n_large)

Original array: [46 25 22 49 57  6 53 65]
5 largest values: [57 65 53 49 46]


# 15.How to create a record array from a regular array?

In [35]:
import numpy as np
rarray = np.array([(1, 'nani', 25),
                           (2, 'palav', 30),
                           (3, 'krish', 35)],
                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
record_array = np.array(rarray.tolist(), dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
print("ID:", record_array['ID'])
print("Name:", record_array['Name'])
print("Age:", record_array['Age'])

ID: [1 2 3]
Name: ['nani' 'palav' 'krish']
Age: [25 30 35]


# 16. How to swap two rows of an array?

In [40]:
import numpy as np
matrix = np.array([[9, 6, 8],
                   [4, 3, 2],
                   [5, 1, 7]])

matrix[0], matrix[2] = matrix[2].copy(), matrix[0].copy()
print(matrix)


[[5 1 7]
 [4 3 2]
 [9 6 8]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [41]:
import numpy as np
original = np.arange(12)
reshaped = original.reshape(3, 4)
next_dimension = reshaped.reshape(3, 4, 1)
print("Original Array (1D):")
print(original)
print("\nReshaped Array (2D):")
print(reshaped)
print("\nReshaped to Next Dimension (3D):")
print(next_dimension)

Original Array (1D):
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (2D):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to Next Dimension (3D):
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
